### ISSUE TITLE
More compact and informative README

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/CovidTimelineCanada#93]
I've made a few commits recently aimed at making the README more compact, with the most relevant information out front, along with the making the `docs` directory more useful:

- Moved the section "Detailed description of data sources" to `docs/data_sources/data_sources.md` (e908fdcb88ca0823b198f5432d3806ee0377d6bd)
- Moved BibTeX citation file into `docs/citation` (725f3fda22f007cc6ed60c8dce61a9d460dae3b5)
- Moved the section "Transitioning from `Covid19Canada`" to `docs/transitioning_from_Covid19Canada` (386f97ac6d3c0f811ee171570d610d064056fe40)

There are a few other changes I'd like to make:

- [x] Turn "Available datasets" into a table with definitions for each metric, definitions for `value` and `value_daily` for each metric (#51) and the file names for each geographic level (currently in "Included datasets" section)
- [x] Add more information on dates that provinces stopped reporting health region-level data (currently reported without date information in the "Getting started" section
- [x] Replacing the plots in the "Included datasets" section/the [`CovidTimelineCanadaPlots`](https://github.com/ccodwg/CovidTimelineCanadaPlots) repository with a basic JavaScript dashboard (#12)
- [x] Document the existence of and reasons for impossible values, rather than removing these by postprocessing (#1)
- [x] Add brief philosophy of dataset construction
- [ ] Add brief history and alternative names for dataset (e.g., opencovid.ca dataset)
- [ ] Mention of historical features such as the API should be moved to the technical report (#133)
